name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache deps
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: deps
          key: deps-${{ hashFiles('deps.txt') }}

      - name: Download deps
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          set -e
          mkdir -p deps
          for i in {1..3}; do
            failed=0
            while read -r url file; do
              [ -z "$url" ] && continue
              echo "Attempt $i: Downloading $file"
              if ! wget -vO "deps/$file" "$url"; then
                echo "Failed: $file"
                failed=1
              fi
            done < deps.txt
            [ "$failed" -eq 0 ] && exit 1
            echo "Waiting before retry $((i+1))..."
            sleep 300
          done

      - name: Generate dir listing
        run: | 
          ls deps | awk '{ print "<a href=\"" $0 "\">" $0 "</a>" }' > deps/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
