name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache deps
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: deps
          key: deps-${{ hashFiles('deps.txt') }}

      - name: Download deps
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          set -e
          mkdir -p deps
          max_attempts=3
          delay=60

          while read -r url file; do
            [ -z "$url" ] && continue

            for i in $(seq 1 "$max_attempts"); do
              echo "Attempt $i: Downloading $file"
              if wget --progress=dot:mega -vO "deps/$file" "$url"; then
                echo "Downloaded $file"
                break
              elif [ "$i" -lt "$max_attempts" ]; then
                echo "Failed to download $file, retrying in $delay seconds..."
                sleep "$delay"
              else
                echo "ERROR: Failed to download $file after $max_attempts attempts"
                exit 1
              fi
            done
          done < deps.txt


      - name: Generate dir listing
        run: | 
          {
          echo "<!DOCTYPE html><html><head></head><body>"
          ls deps | awk '{ print "<li><a href=\"" $0 "\">" $0 "</a></li>" }'
          echo "</body></html>"
          } > deps/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
